on chat:
	if message contains ":skull:":
		replace all ":skull:" in message with "💀"
		send "[&aEmojiMC&r] Converted :skull: into an emoji!" to player
	if message contains ":happy:":
		replace all ":happy:" in message with "☻"
		send "[&aEmojiMC&r] Converted :happy: into an emoji!" to player
	if message contains ":music_1:":
		replace all ":music_1:" in message with "♪"
		send "[&aEmojiMC&r] Converted :music_1: into an emoji!"
	if message contains ":music_2:":
		replace all ":music_2:" in message with "♫"
		send "[&aEmojiMC&r] Converted :music_2: into an emoji!"
	if message is ":???:":
		set message to "&4&k???"
		send "[&a&kEmojiMC&r] &kConverted &r:???:&k into an emoji!"
	if message contains ":happy_transparent:" or ":happy_1:":
		send "[&aEmojiMC&r] Converted all known emojis in your message into an emoji!"
		replace all ":happy_1:" or "happy_transparent" in message with "☺"
	if message contains ":pickaxe:" or ":pick:":
		send "[&aEmojiMC&r] Converted all known emojis in your message into an emoji!"
		replace all ":pick:" or ":pickaxe:" in message with "⛏"
	if message contains ":diamond:":
		replace all ":diamond:" in message with "💎"
		send "[&aEmojiMC&r] Converted :diamond: into an emoji!"
	if message contains ":pig:":
		replace all ":pig:" in message with "🐖"
		send "[&aEmojiMC&r] Converted :pig: into an emoji!"
	if message contains ":cat:":
		replace all ":cat:" in message with "🐈"
		send "[&aEmojiMC&r] Converted :cat: into an emoji!"
	if message contains ":wolf:" or ":dog:":
		send "[&aEmojiMC&r] Converted all known emojis in your message into an emoji!"
		replace all ":wolf:" or ":dog:" in message with "🐺"
	if message contains ":ladder:":
		replace all ":ladder:" in message with "🪜"
		send "[&aEmojiMC&r] Converted :ladder: into an emoji!"
	if message contains ":chicken:" or ":chicken_laying_egg:":
		send "[&aEmojiMC&r] Converted all known emojis in your message into an emoji!"
		replace all ":chicken:" or "chicken_laying_egg" in message with "🐔"
	if message contains ":fire:":
		replace all ":fire:" in message with "🔥"
		send "[&aEmojiMC&r] Converted :fire: into an emoji!"
	if message contains ":brick:":
		replace all ":brick:" in message with "🧱"
		send "[&aEmojiMC&r] Converted :brick: into an emoji!"
	if message is "::":
		cancel event
		send "[&aEmojiMC&r] :music_1:, :music_2:, :happy:, :happy_transparent:/:happy_1:, :skull:, :&k???&r:, :pick:/:pickaxe:, :pig:, :diamond:, :cat:, :wolf:/:dog:, :ladder:, :chicken:/:chicken_laying_egg:, :fire:, :brick:"
